apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bars.stable.example.com
spec:
  group: stable.example.com
  versions:
  - name: "v1"
    served: true
    storage: true
  names:
    kind: Bar
    plural: bars
  scope: Namespaced
  validation:
    openAPIV3Schema:
      type: object
      properties:
        foo:
          type: array
