// +build !ignore_autogenerated

/*
Copyright 2016 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by openapi-gen. Do not edit it manually!

package model

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/openapi-linter/model.Car": {
			Schema: spec.Schema{
				SchemaProps: spec.SchemaProps{
					Description: "Car is a simple car model.",
					Properties: map[string]spec.Schema{
						"Color": {
							SchemaProps: spec.SchemaProps{
								Type:   []string{"string"},
								Format: "",
							},
						},
						"Capacity": {
							SchemaProps: spec.SchemaProps{
								Type:   []string{"integer"},
								Format: "int32",
							},
						},
					},
					Required: []string{"Color", "Capacity"},
				},
			},
			Dependencies: []string{},
		},
		"k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/openapi-linter/model.MinimalPod": {
			Schema: spec.Schema{
				SchemaProps: spec.SchemaProps{
					Description: "MinimalPod is a minimal pod.",
					Properties: map[string]spec.Schema{
						"name": {
							SchemaProps: spec.SchemaProps{
								Type:   []string{"string"},
								Format: "",
							},
						},
						"PodSpec": {
							SchemaProps: spec.SchemaProps{
								Ref: ref("k8s.io/api/core/v1.PodSpec"),
							},
						},
					},
					Required: []string{"name", "PodSpec"},
				},
			},
			Dependencies: []string{
				"k8s.io/api/core/v1.PodSpec"},
		},
	}
}
